<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net35</TargetFramework>
    <AssemblyName>DIYLevelFastInit</AssemblyName>
    <RootNamespace>DIYLevelFastInit</RootNamespace>
    <LangVersion>7.3</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>none</DebugType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net35" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>D:\Games\Steam Games\steamapps\common\Overcooked! 2\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>D:\Games\Steam Games\steamapps\common\Overcooked! 2\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>D:\Games\Steam Games\steamapps\common\Overcooked! 2\Overcooked2_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>D:\Games\Steam Games\steamapps\common\Overcooked! 2\Overcooked2_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>D:\Games\Steam Games\steamapps\common\Overcooked! 2\Overcooked2_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>D:\Games\Steam Games\steamapps\common\Overcooked! 2\Overcooked2_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="OC2DIYLevel">
      <HintPath>D:\Games\Steam Games\steamapps\common\Overcooked! 2\BepInEx\plugins\OC2DIYLevel\OC2DIYLevel.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="LevelEditorStub">
      <HintPath>D:\Games\Steam Games\steamapps\common\Overcooked! 2\BepInEx\plugins\OC2DIYLevel\LevelEditorStub.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
